config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'

end

app/models/photo.rb
require 'carrierwave/orm/activerecord'

class Photo < ActiveRecord::Base
  belongs_to :post
  mount_uploader :photo, PhotoUploader

=begin
 before_create :generate_id

  def photo?
    content_type.start_with? 'image'
  end

  private

  def generate_id
    begin
      generated_id = rand(1..INTEGER)
    end until !Attach.exists?(generated_id)
    self.id = generated_id
  end
=end

end

app/models/post.rb
class Post < ActiveRecord::Base

belongs_to :user
has_many :photos
accepts_nested_attributes_for :photos, allow_destroy: true

  validates :title,
  :presence => true, 
  :length => {:minimum => 1, :maximum => 254}

  validates :description,
    :presence => true,
    :length => {:minimum => 1, :maximum => 511}
 
  validates :phone,
    :length => {:minimum => 6, :maximum => 12},
    :allow_blank => true
  #  format: { with: /\A(?:\+?|\b)(?=.*?[1-9]|\s)[0-9()-|\s]+\Z/ }
                   
  validates :email,
    :allow_blank => true,
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

  validates :address,
    :length => {:minimum => 1, :maximum => 254},
    :allow_blank => true

  validates :url,
    :length => {:minimum => 1, :maximum => 254},
    :allow_blank => true,
    :format => URI::regexp(%w(http https))

end

app/models/user.rb
class User < ActiveRecord::Base

has_many :posts
has_many :photos

	def self.from_omniauth(auth)
		@user = find_or_initialize_by(facebook_id: auth.uid)
		@user.attributes = {
			name: auth[:info][:name],
			email: auth[:info][:email],
			photo: auth[:info][:image],
			login: auth[:info][:urls],
			oauth_token: auth[:credentials][:token],
			oauth_expires_at: DateTime.strptime(auth[:credentials][:expires_at].to_s,'%s')
		}
		@user.save!
		@user
	end

	def admin?
		["lerarunge@gmail.com", "kolomeetz@gmail.com"].include?(email) 
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

   def require_user
    if current_user.nil?
      flash[:error] = "You must be logged in to access this section"
      redirect_to posts_path # halts request cycle
    end
    # redirect_to posts_path unless current_user
   end 

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

def create
    @photo = Photo.new(photo_params)
    @photo.save
end

def update
    @photo = Photo.new(photo_params)
    @photo.save
end

end

app/controllers/posts_controller.rb
	class PostsController < ApplicationController

before_action :require_user, only: [:new, :edit, :update, :destroy, :create]
before_action :set_post, only: [:show, :edit, :update, :destroy]
before_action only: [:edit, :update, :destroy] { require_owner(@post) }

	def index
		@posts = Post.all
	end

	def show	
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(post_params)
		@post.user = current_user
		if @post.save
			if params[:photos]
        params[:photos].each { |photo|
          @post.photos.create(photo: photo)
        }
        end
			redirect_to @post
		else
			render :new
		end
	end

	def edit
	end

	def update

		if @post.update(post_params)
			if params[:photos]
        params[:photos].each { |photo|
          @post.photos.create(photo: photo)
        }
        end
			redirect_to @post
		else
			render :edit
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :description, :phone, :email, :address, :url, :author, photos_attributes:[:id,:_destroy])
	end

	def post_belongs_to_user?(post)
		post.user == current_user
	end

	def set_post
		@post = Post.find(params[:id])
	end

	def require_owner(post)
      unless post_belongs_to_user?(post) || current_user && current_user.admin?
        flash[:error] = "ЭТО НЕ ВАШ ПОСТ, НЕ ВАШ!"
        redirect_to posts_path # halts request cycle
      end
    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def create
	user = User.from_omniauth(env["omniauth.auth"])
	session[:user_id] = user.id
	redirect_to root_url
#render inline: "<%= debug request.env[\"omniauth.auth\"]%>"
end

def destroy
	session[:user_id] = nil
	redirect_to root_url
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rult</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> 
</head>

<body class="body_background">


<!-- <div class="header">
      <ul class="nav">
          <% if current_user %>
            <li class="button"><%= link_to "Create new adv", new_post_path %></li>
            <li>Sign in as <%= current_user.name %></li>
            <li class="button"><%= link_to "Sign out", signout_path%></li>
          <% else %>
            <li class="button"><%= link_to "Sign in with Facebook", "/auth/facebook"%></li>
          <% end %>  
      </ul>
</div> -->


<nav class="navbar navbar-dark bg-inverse">
  <%= link_to "ruLT", '/', class: "navbar-brand" %>
    <ul class="nav navbar-nav pull-xs-right">
          <% if current_user %>
            <%= image_tag current_user.photo, class: "avatar_header" %>
            <!-- size: "36x36", style: "float:right; margin-left: 15px" %>   -->
            <li class="nav-item"><%= link_to "Create new adv", new_post_path, class: "btn btn-secondary-outline" %></li>
            <li class="nav-item"><%= link_to "Sign out", signout_path, class: "btn btn-secondary-outline" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign in with Facebook", "/auth/facebook", class: "btn btn-secondary-outline" %></li>
          <% end %>  
      </ul>
</nav>



<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <%= flash[:error] %>
      <%= yield %>
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>

</body>
</html>

app/views/posts/_actions.html.erb
<% if current_user && (post.user == current_user || current_user.admin?) %>
  <%= link_to "Edit", edit_post_path(post), class: "card-link, author_links" %>
  <%= link_to "Delete adv", post_path(post), method: :delete, class: "card-link, author_links" %>
<%end%>

app/views/posts/_contacts.html.erb
  <ul class="contacts">    
    <li><%= link_to nil, post.url, target: "_blank" if post.url %></li>
    <li><%= post.try :email %></li>
    <li><%= post.try :phone %></li>
    <li><%= post.try :address %></li>
  </ul>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row card card-block">
    <div class="col-md-12" style="background-color: #fff;">
      <%= form_for(@post, :html => {:multipart => true}) do |f| %>  
        <% if @post.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@post.errors.count, "error") %> prohibited
              this article from being saved:
            </h2>
            <ul>
              <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

  <div class="col-md-10">
    <fieldset class="form-group">     
  	  <%= f.label :title, "Название услуги или компании*" %>
      <%= f.text_field :title, class: "form-control", placeholder: "Например, teampact.io" %>
    </fieldset>

    <fieldset class="form-group"> 
      <%= f.label :description, "Описание*" %>
      <%= f.text_area :description, class: "form-control" %>
    </fieldset>

    <fieldset class="form-group"> 
      <%= f.label :phone, "Телефон" %>
      <%= f.text_field :phone, class: "form-control" %>
    </fieldset>

    <fieldset class="form-group">     
      <%= f.label :email, "Электронная почта" %>
      <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
    </fieldset>

    <fieldset class="form-group"> 
      <%= f.label :address, "Адрес" %>
      <%= f.text_field :address, class: "form-control" %>
    </fieldset>

    <fieldset class="form-group"> 
      <%= f.label :url, "Адрес сайта" %>
      <%= f.text_field :url, class: "form-control"%>
    </fieldset>

    <fieldset class="form-group"> 
      <%= f.label :url, "Добавить фото:" %>
      <%= file_field_tag "photos[]", type: :photo, multiple: true %>
    </fieldset>
  
    <% if @post.photos %>
         <p>Поставьте галочки, чтобы удалить фотографии.</p>
      <div class="photo-block">
      <%= f.fields_for :photos do |photo_form| %>
        <div class="photo">
          <%= image_tag photo_form.object.photo.thumb.url %>
          <%= photo_form.check_box :_destroy%>
        </div>
      <% end %>
      </div>
    <% end %>

    <%= f.submit class: "btn btn-success" %>

 <% end %>
  </div>

     </div>

   </div>
 </div>

app/views/posts/_photo.html.erb
<div class="avatar_photo">
  <% if post.user %>
    <%= image_tag post.user.photo, class: "avatar" %></br>
    <%= post.user.name %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
      <% @posts.each do |post|%> 
          <div class="card card-block row">
            <div class="col-xs-3">
             <%= render "photo", post: post %>
            </div>
            <div class="col-xs-9">
              <h4 class="card-title"><%= post.title %></h4> 
              <p class="post_description"><%= post.description %></p>
              <div style="float: right;"><%= link_to "Read more", post_path(post), class: "card-link, author_links" %></div>
            <div style="margin-top: 50px">    
              <%= render "contacts", post: post %>
            </div>

            <%= render "actions", post: post %>
            </div>
          </div>
      <% end %> 

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<div class="card card-block">
	<div class="row col-xs-12 to-all-photos" style="padding-bottom: 20px">
		<%= link_to "<—— Ко всем объявлениям", posts_path %>
	</div>
	<div class="row">
        <div class="col-xs-3">
            <%= render "photo", post: @post %>
        </div>
        <div class="col-xs-9">
            <h4 class="card-title"><%= @post.title %></h4> 
            <p><%= @post.description %></p>
               
            <% @post.photos.each do |photo| %>
                <%= link_to photo.photo.url do %>
                <%= image_tag photo.photo.thumb.url, class: "photo"%>
                <% end %>
            <% end %>

            <div style="margin-top: 0px">    
				<%= render "contacts", post: @post %>
            </div>
              
			<%= render "actions", post: @post %>
         </div>
     </div>
</div>